language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t matthiasjensen/react-test -f ./client/Dockerfile.dev ./client
    
script:
    - docker run -e CI=true matthiasjensen/react-test npm test

after_success:
    - docker build -t matthiasjensen/multi-client ./client
    - docker build -t matthiasjensen/multi-nginx ./nginx
    - docker build -t matthiasjensen/multi-server ./server
    - docker build -t matthiasjensen/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push matthiasjensen/multi-client
    - docker push matthiasjensen/multi-nginx
    - docker push matthiasjensen/multi-server
    - docker push matthiasjensen/multi-worker

deploy:
    provider: elasticbeanstalk
    region: 'eu-central-1'
    app: 'multi-docker'
    env: 'MultiDocker-env'
    bucket_name: 'elasticbeanstalk-eu-central-1-104811627402'
    bucket_path: 'docker-multi'
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY